openapi: 3.0.0
info:
  title: Bank API
  version: 1.0.0
  description: API for managing bank accounts and transactions.
paths:
  /accounts:
    post:
      summary: Create a new account
      description: Creates a new account with a number and initial balance.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: object
                  properties:
                    number:
                      type: integer
                      description: The account number.
                      example: 123456
                    balance:
                      type: number
                      description: The initial balance of the account.
                      example: 1000.00
              required:
                - account
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '422':
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/{number}:
    get:
      summary: Get account details
      description: Retrieves the details of an account by account number.
      parameters:
        - name: number
          in: path
          required: true
          schema:
            type: integer
          description: The account number.
      responses:
        '200':
          description: Account details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /transactions:
    post:
      summary: Create a new transaction
      description: Creates a new transaction for a specific account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction:
                  type: object
                  properties:
                    account_number:
                      type: integer
                      description: The account number of the account.
                      example: 123456
                    payment_type:
                      type: string
                      description: The type of payment (e.g., 'credit', 'debit', 'pix').
                      example: 'D'
                    value:
                      type: number
                      description: The amount of the transaction.
                      example: 100.00
              required:
                - transaction
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created transaction.
                  account_number:
                    type: integer
                    description: The account number of the account.
                  payment_type:
                    type: string
                    description: The type of payment.
                  value:
                    type: number
                    description: The amount of the transaction.
                  created_at:
                    type: string
                    format: date-time
                    description: The timestamp when the transaction was created.
                  updated_at:
                    type: string
                    format: date-time
                    description: The timestamp when the transaction was last updated.
        '404':
          description: Account not found or transaction validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '422':
          description: Validation errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the transaction.
        account_number:
          type: integer
          description: The account number associated with the transaction.
        payment_type:
          type: string
          description: The type of payment.
        value:
          type: number
          description: The amount of the transaction.
        created_at:
          type: string
          format: date-time
          description: The timestamp when the transaction was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the transaction was last updated.
    Account:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the account.
        number:
          type: integer
          description: The account number.
        balance:
          type: number
          description: The balance of the account.
        created_at:
          type: string
          format: date-time
          description: The timestamp when the account was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the account was last updated.
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
